export const navLinks = [
  { navLinkId: "#", scrollToId: "onboardContent" },
  { navLinkId: "A", scrollToId: "aSectionContent" },
  { navLinkId: "B", scrollToId: "bSectionContent" },
  { navLinkId: "C", scrollToId: "cSectionContent" },
  // { navLinkId: "D", scrollToId: "dSectionContent" },
  // { navLinkId: "E", scrollToId: "eSectionContent" },
  // { navLinkId: "F", scrollToId: "fSectionContent" },
  // { navLinkId: "G", scrollToId: "gSectionContent" },
  // { navLinkId: "H", scrollToId: "hSectionContent" },
  // { navLinkId: "I", scrollToId: "iSectionContent" },
  // { navLinkId: "J", scrollToId: "jSectionContent" },
  // { navLinkId: "K", scrollToId: "kSectionContent" },
  // { navLinkId: "L", scrollToId: "lSectionContent" },
  // { navLinkId: "M", scrollToId: "mSectionContent" },
  // { navLinkId: "N", scrollToId: "nSectionContent" },
  // { navLinkId: "O", scrollToId: "oSectionContent" },
  // { navLinkId: "P", scrollToId: "pSectionContent" },
  // { navLinkId: "Q", scrollToId: "qSectionContent" },
  // { navLinkId: "R", scrollToId: "rSectionContent" },
  // { navLinkId: "S", scrollToId: "sSectionContent" },
  // { navLinkId: "T", scrollToId: "tSectionContent" },
  // { navLinkId: "U", scrollToId: "uSectionContent" },
  // { navLinkId: "V", scrollToId: "vSectionContent" },
  // { navLinkId: "W", scrollToId: "wSectionContent" },
  // { navLinkId: "X", scrollToId: "xSectionContent" },
  // { navLinkId: "Y", scrollToId: "ySectionContent" },
  // { navLinkId: "Z", scrollToId: "zSectionContent" },
];
